dist: bionic
language: php

sudo: true

php:
  - 7.3

install:
  - travis_retry composer self-update
  - travis_retry composer clear-cache
  - composer create-project --prefer-dist laravel/laravel

script:
  - ./vendor/bin/phpunit --verbose
